config/routes.rb
Rails.application.routes.draw do
  resources :hospitals do
      member do
        post :create_doctor
        delete :delete_doctor
      end
    resources :patients do
      member do
        post :create_doctor
        delete :delete_doctor
        patch :waiting_room
        patch :doctor_checkup
        patch :xray_appointment
        patch :surgery_appointment
        patch :pay_bills
        patch :leaving
      end
            resources :meds
    end
  end

   root 'home#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :Doctorable, polymorphic: true
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  has_many :patients, dependent: :destroy
  has_many :doctors, as: :doctorable
end

app/models/med.rb
class Med < ActiveRecord::Base
  belongs_to :patient
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  validate :check_dob
  belongs_to :hospital
  has_many :meds, dependent: :destroy
  has_many :doctors, as: :doctorable
  def check_dob
    gap = 10.years.ago
    if self.dob > gap
      errors.add(:dob, "need's to be older 10 yrs old")
    end
  end
  include Workflow
  workflow do
    state :waiting_room do
      event :wait, transitions_to: :waiting_room
      event :checkup, transitions_to: :doctor_checkup
      event :xray, transitions_to: :xray_appointment
      event :surgery, transitions_to: :surgery_appointment
      # all but pay/leave
    end
    state :doctor_checkup do
      event :wait, transitions_to: :waiting_room
      event :checkup, transitions_to: :doctor_checkup
      event :xray, transitions_to: :xray_appointment
      event :surgery, transitions_to: :surgery_appointment
      event :pay, transitions_to: :pay_bills
      event :leave, transitions_to: :leaving
      # all
    end
    state :xray_appointment do
      event :wait, transitions_to: :waiting_room
      event :checkup, transitions_to: :doctor_checkup
      event :xray, transitions_to: :xray_appointment
      event :surgery, transitions_to: :surgery_appointment
      event :pay, transitions_to: :pay_bills
      event :leave, transitions_to: :leaving
      # all but doctor_checkup
    end
    state :surgery_appointment do
      event :checkup, transitions_to: :doctor_checkup
      event :xray, transitions_to: :xray_appointment
      event :surgery, transitions_to: :surgery_appointment
      event :pay, transitions_to: :pay_bills
      event :leave, transitions_to: :leaving
      # all but waiting_room
    end
    state :pay_bills do
      event :leave, transitions_to: :leaving
      # leave
    end
    state :leaving do
      # nothing
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
    if !params[:search].blank?
      @hospitals = Hospital.where("name LIKE ?", "%#{params[:search]}%")
    else  
    @hospitals = Hospital.all
    end
  end
  def show
    set_hospital
    @patients = @hospital.patients
    @doctor = Doctor.new
  end
  def create_doctor
    set_hospital
    @doctor = @hospital.doctors.create doctor_params
    redirect_to hospital_path(@hospital)
  end
  def delete_doctor
    @doctor = Doctor.find params[:id]
    @doctor.destroy
    redirect_to hospital_path
  end
  def new
    @hospital = Hospital.new
  end
  def edit
    set_hospital
  end
  def create
    @hospital = Hospital.new(hospital_params)
    if @hospital.save
      flash[:notice] = "Hospital was created"
      redirect_to hospitals_path(@hospital)
    else
      flash[:error] = "Hospital was not created"
      render :new
    end
  end
  def update
    set_hospital
    @hospital.update_attributes hospital_params
    redirect_to hospitals_path
  end
  def destroy
    set_hospital
    @hospital.destroy
    redirect_to hospitals_path
  end
private
  def set_hospital
    @hospital = Hospital.find(params[:id])
  end
  def doctor_params
    params.require(:doctor).permit(:name)
  end
  def hospital_params
    params.require(:hospital).permit(:name, :location)
  end
end

app/controllers/meds_controller.rb
class MedsController < ApplicationController
  def index
    set_hospital
    set_patient
    if !params[:search].blank?
      @meds = Med.where("name LIKE ?", "%#{params[:search]}%")
    else  
    @meds = Med.all
    end
  end
  def show
    set_hospital
    set_patient
    set_med
  end
  def new
    set_hospital
    set_patient
    @med = @patient.meds.new
  end
  def create
    set_hospital
    set_patient
    @med = @patient.meds.create med_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end
  def edit
    set_hospital
    set_patient
    set_med
  end
  def update
    set_hospital
    set_patient
    set_med    
    @med.update_attributes med_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end
  def destroy
    set_med
    @med.destroy
    redirect_to hospital_patient_meds_path(@hospital, @patient, @med)
  end
private
  def set_hospital
    @hospital = Hospital.find(params[:hospital_id])
  end
  def set_patient
    @patient = Patient.find(params[:patient_id])
  end
  def set_med
    @med = Med.find params[:id]
  end
  def med_params
    params.require(:med).permit(:name, :direction)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_hospital, only: [:waiting_room, :doctor_checkup, :xray_appointment, :surgery_appointment, :pay_bills, :leaving]
  before_action :set_patient, only: [:waiting_room, :doctor_checkup, :xray_appointment, :surgery_appointment, :pay_bills, :leaving]
  def index
    set_hospital
    if !params[:search].blank?
      @patients = Patient.where("firstname LIKE ?", "%#{params[:search]}%")
    else  
    @patients = Patient.all
    end
  end
  def show
    set_hospital
    set_patient
    @meds = @patient.meds
    @doctor = Doctor.new
  end
  def create_doctor
    set_hospital
    set_patient
    @doctor = @patient.doctors.create doctor_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end
  def delete_doctor
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to hospital_path(@hospital, @patient)
  end
  def waiting_room
    @patient.wait!
    redirect_to hospital_patients_path(@hospital)
  end
  def doctor_checkup
    @patient.checkup!
    redirect_to hospital_patients_path(@hospital)
  end
  def xray_appointment
    @patient.xray!
    redirect_to hospital_patients_path(@hospital)
  end
  def surgery_appointment
    @patient.surgery!
    redirect_to hospital_patients_path(@hospital)
  end
  def pay_bills
    @patient.pay!
    redirect_to hospital_patients_path(@hospital)
  end
  def leaving
    @patient.leave!
    redirect_to hospital_patients_path(@hospital)
  end
  def new
    set_hospital
    @patient = Patient.new
  end
  def create
    set_hospital
    @patient = @hospital.patients.create patient_params
    redirect_to hospital_path(@hospital)
  end
  def edit
    set_hospital
    set_patient
  end
  def update
    set_hospital
    set_patient
    @patient.update_attributes patient_params
    redirect_to hospital_path(@hospital)
  end
  def destroy
    set_patient
    @patient.destroy
    redirect_to hospital_patients_path(@hospital)
  end

private
  def set_hospital
    @hospital = Hospital.find(params[:hospital_id])
  end
  def set_patient
    @patient = Patient.find params[:id]
  end
  def doctor_params
    params.require(:doctor).permit(:name)
  end
  def patient_params
    params.require(:patient).permit(:firstname, :lastname, :dob, :symptoms, :gender, :bloodtype, :workflow_state, :hospital_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/_sidebar.html.haml
%br
%i.btn.btn-default
  = link_to "Hospital List", hospitals_path
  %span.glyphicon.glyphicon-plus
/ %br
/ %i.button
/   = link_to 'Patients List', hospital_patients_path(@hospital)
/ %br

app/views/home/index.html.haml
%div{ class: "topbar"}
  %h1 Hospital Simulation

app/views/hospitals/_form.html.haml
= form_for (@hospital) do |f|
  - if @hospital.errors.any?
    - @hospital.errors.full_messages.each do |message|
      = message
      %br/
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :location
  = f.text_field :location
  %br/
  = f.submit

app/views/hospitals/_sidebar.html.haml
%br
%i.btn.btn-default
  = link_to 'New Hospital', new_hospital_path(@hospital)
%br
%i.btn.btn-default
  = link_to 'Show Hopsitals', hospitals_path

app/views/hospitals/edit.html.haml
%h1 Editing Hospital
= render 'form'
= link_to 'Back', hospitals_path

app/views/hospitals/index.html.haml
%div{ class: "topbar"}
  %h1 Hospitals
= form_tag hospitals_path, method: :get, class: "form-search", role: "search" do
  .input-group
    =text_field_tag 'search', params[:search], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %span.glyphicon.glyphicon-search
%div{class: "info"}
  - @hospitals.each do |hospital|
    .btn.btn-default
      = link_to hospital_path(hospital) do
        = hospital.name
    = link_to 'Edit', edit_hospital_path(hospital), class: "back"
    = link_to 'Destroy', hospital_path(hospital), method: :delete, class: "back"
    %br
%div
    

app/views/hospitals/new.html.haml
%h1 New Hospital
= render 'form'
= link_to 'Back', hospitals_path

app/views/hospitals/show.html.haml
%div{ class: "topbar"}
  %h1 Hospital

%h4
  Name: #{@hospital.name}
%h4
  Location: #{@hospital.location}
%br/
%h3 This Hospitals Patients
- @patients.each do |patient|
  .btn.btn-default
    = link_to hospital_patient_path(@hospital, patient) do
      = patient.lastname
      ,
      = patient.firstname
  %br/
%div
  = link_to "Add Patient", new_hospital_patient_path(@hospital, @patient)
%br
%h2 Create Doctor
%div{ class: "doctor"}
  =form_for @doctor, url: create_doctor_hospital_path(@hospital) do |f|
    = f.label :name
    = f.text_field :name
    = f.submit
    %br
  - @hospital.doctors.each do |doctor|
    = doctor.name
    = link_to 'Destroy', delete_doctor_hospital_path(doctor), method: :delete
    %br

app/views/layouts/_navbar.html.haml
%ul.nav.navbar-nav
  %ul.nav.navbar-nav.navbar-right
    LOGIN STUFF

app/views/layouts/_sidebar.html.haml
%i.btn.btn-default
  = link_to root_path do
    %i.glyphicon.glyphicon-home
= render 'sidebar'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Day13
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
        = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top{:role => "navigation"}
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar 
          %span.icon-bar
      .nav-collapse.collapse
        = render 'layouts/navbar'
    .container-sidebar
      .row
        .col-sm-3.sidebar-style
          = render 'layouts/sidebar'
      .container
        .row
          .body-content-style
            - if flash[:notice]
              %h5#notice= flash[:notice]
            - if flash[:error]
              %h5#error= flash[:error]
            = yield

app/views/meds/_form.html.haml
= form_for [@hospital, @patient, @med] do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.label :direction
  = f.text_field :direction
  %br/
  = f.submit
  |
  \#{link_to "Back", hospital_patient_meds_path}

app/views/meds/_sidebar.html.haml
%br
%i.btn.btn-default
  = link_to 'Show meds', hospital_patient_meds_path(@hospital, @patient)
%br
%i.btn.btn-default
  = link_to 'New Med', new_hospital_patient_med_path

app/views/meds/edit.html.haml
%h1 Edit Medication
= render 'form'

app/views/meds/index.html.haml
%div{ class: "topbar"}
  %h1 Med List
= form_tag hospital_patient_meds_path, method: :get, class: "form-search", role: "search" do
  .input-group
    =text_field_tag 'search', params[:search], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %span.glyphicon.glyphicon-search  
- @meds.each do |med|
  %div
    = med.name
    = med.direction
    = link_to 'Edit', edit_hospital_patient_med_path(@hospital, @patient, med)
    = link_to 'Destroy', hospital_patient_med_path(@hospital, @patient, med), method: :delete
%div
  = link_to "Add Med", new_hospital_patient_med_path

app/views/meds/new.html.haml
%h1 New Medication
= render 'form'

app/views/meds/show.html.haml
%h2
  Name:
  = @med.name
  %br
  Directions:
  = @med.direction
#{link_to 'Edit', edit_hospital_patient_med_path(@hospital, @patient, @med)}
#{link_to 'Destroy', hospital_patient_med_path(@hospital, @patient, @med), method: :delete}

app/views/patients/_form.html.haml
= form_for [@hospital, @patient] do |f|
  - if @patient.errors.any?
    - @patient.errors.full_messages.each do |message|
      = message
    %br/
  = f.label :firstname
  = f.text_field :firstname
  %br/
  = f.label :lastname
  = f.text_field :lastname
  %br/
  = f.label :dob
  = f.date_field :dob
  %br/
  = f.label :symptoms
  = f.text_field :symptoms
  %br/
  = f.label :male
  = f.radio_button 'gender', 'male'
  = f.label :female
  = f.radio_button 'gender', 'female'
  %br/
  = f.label :bloodtype
  = f.select :bloodtype, options_for_select([ "A", "B", "AB", "O"]), include_blank: "--I dont know--"
  %br/
  = f.submit
  |
  \#{link_to "Back", hospitals_path}

app/views/patients/_sidebar.html.haml
%br
%i.btn.btn-default
  = link_to 'New Patient', new_hospital_patient_path
%br
%i.btn.btn-default
  = link_to 'Show Patients', hospital_patients_path

app/views/patients/edit.html.haml
%h1 Edit Patient Information
= render 'form'

app/views/patients/index.html.haml
%h1 Patients
= form_tag hospital_patients_path, method: :get, class: "form-search", role: "search" do
  .input-group
    =text_field_tag 'search', params[:search], class: "form-control", id: "srch-term", placeholder: "Search"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %span.glyphicon.glyphicon-search  
- @patients.each do |patient|
  %div
    |||||||||
    = patient.workflow_state
    |||||||||
    hospital_id:
    \#{patient.hospital_id} ||
    \#{patient.firstname}#{patient.lastname}#{patient.dob}#{patient.symptoms}#{patient.gender}#{patient.bloodtype}
    #{link_to 'Show', hospital_patient_path(@hospital, patient)}
    #{link_to 'Edit', edit_hospital_patient_path(@hospital, patient)}
    #{link_to 'Destroy', hospital_patient_path(@hospital, patient), method: :delete}
    -if patient.waiting_room?
      = link_to "wait", waiting_room_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "checkup", doctor_checkup_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "xray", xray_appointment_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "surgery", surgery_appointment_hospital_patient_path(@hospital, patient), method: :patch
    -if patient.doctor_checkup? || patient.xray_appointment?
      = link_to "wait", waiting_room_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "checkup", doctor_checkup_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "xray", xray_appointment_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "surgery", surgery_appointment_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "pay", pay_bills_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "leave", leaving_hospital_patient_path(@hospital, patient), method: :patch
    -if patient.surgery_appointment?
      = link_to "checkup", doctor_checkup_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "xray", xray_appointment_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "surgery", surgery_appointment_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "pay", pay_bills_hospital_patient_path(@hospital, patient), method: :patch
      = link_to "leave", leaving_hospital_patient_path(@hospital, patient), method: :patch
    -if patient.pay_bills?
      = link_to "leave", leaving_hospital_patient_path(@hospital, patient), method: :patch

app/views/patients/new.html.haml
%h1 New Patient
= render 'form'

app/views/patients/show.html.haml
%div{ class: "topbar"}
  %h1 Patient
%h4    
  %div 
    firstname: #{@patient.firstname}
    %br
    lastname: #{@patient.lastname}
    %br
    dob: #{@patient.dob}
    %br
    symptoms: #{@patient.symptoms}
    %br
    gender: #{@patient.gender}
    %br
    bloodtype: #{@patient.bloodtype}
    %br
%h3 Meds
- @meds.each do |med|
  %div
    .btn.btn-default
      = link_to hospital_patient_med_path(@hospital, @patient, med) do
        = med.name
%div
  = link_to "Add Med", new_hospital_patient_med_path(@hospital, @patient, @med)
%h2 Create Doctor
%div{ class: "doctor"}
  =form_for @doctor, url: create_doctor_hospital_patient_path(@hospital, @patient) do |f|
    = f.label :name
    = f.text_field :name
    = f.submit
    %br
  - @patient.doctors.each do |doctor|
    = doctor.name
    = link_to 'Destroy', delete_doctor_hospital_path(doctor), method: :delete
    %br/